---
- include_tasks: ntp-Redhat.yaml
  when: ansible_os_family == 'RedHat' or ansible_os_family == "Centos"

- include_tasks: ntp-Ubuntu.yaml
  when: ansible_os_family == "Ubuntu"





- name: remove lines in ntp.conf
  lineinfile:
    path: /etc/ntp.conf
    regexp: '^server'
    state: absent

- name: add ntp servers to ntp.conf
  lineinfile:
    path: /etc/ntp.conf
    regexp: '^server'
    state: present
    line: |+
      server time1.google.com prefer
      server time2.google.com
      server time3.google.com
      server time4.google.com

- name: Check Time  
  shell: timedatectl
  register: result

- name: Print date time 
  debug:
    msg: "{{ result }}"