---
- include_tasks: ntp-Redhat.yaml
  when: ansible_distribution == 'RedHat' or ansible_distribution == "Centos"

- include_tasks: ntp-Ubuntu.yaml
  when: ansible_distribution == "Ubuntu"
  
- include_tasks: ntp-set.yaml