- name: apt install ntpdate with ubuntu
  apt:
    name: ntp
    state: latest
    update_cache: yes
  when:  ansible_os_family == "Ubuntu"
  register: install_ntp

- name: Control whether NTP is enabled with "Ubuntu"
  shell: /usr/bin/systemctl enable systemd-timesyncd.service
  tags:
      - enable_ntp_control