---
- name: Add go bin dir to $PATH if PATH does not exist
  shell: "cat /etc/profile |grep mariadb | wc -l"
  register: env_mariadb
- debug: msg="{{env_mariadb.stdout}}"

- name: "Add {{ mariadb_bin_path }} to PATH"
  lineinfile:
    path: "{{profile_file}}"
    state: present
    regexp: '(PATH=)(["]?)([\w|\/|\-|\:]+)(\$PATH?)(["]?)$'
    line: '\1\3{{ mariadb_bin_path }}:\4'
    backrefs: yes
  when: env_mariadb.stdout == "0"

- name: source "{{profile_file}}"
  shell: source "{{profile_file}}" && echo $PATH
  become: true
  args:
     executable: /bin/bash
  register: profile_status

- debug: msg="profile={{profile_status.stdout}}"