---
- name: install default mariadb my.cnf
  template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "/etc/{{ item }}"
  with_items:
    - my.cnf

- name: setup mariadb db 
  shell: "/opt/APP/mariadb/scripts/mysql_install_db --user={{mariadb_user}} --datadir={{mariadb_DB_dir}} --basedir={{mariadb_base_path}}/"
  register: install_db_status

- debug: msg="{{install_db_status}}"

- name: copy galera_recovery to bin directory
  template:
    src: "{{ role_path }}/templates/galera_recovery.j2"
    dest: "{{mariadb_bin_path}}/galera_recovery"
    owner: "{{mariadb_user}}"
    group: "{{mariadb_group}}"
    mode: 075my5
    force: true


- name: create mariadb service for systemd
  template:
    src: "{{ role_path }}/templates/mariadb.service.j2"
    dest: /lib/systemd/system/mariadb.service
    owner: root
    group: root
    mode: 0644
  when: ansible_service_mgr == 'systemd'

