---
  - name: get golang file
    vars:
      url: 'https://go.dev/dl/go1.18.1.linux-amd64.tar.gz'
      extra_path: /usr/local/go/bin
    environment:
    PATH: '{{ extra_path }}:{{ ansible_env.PATH }}'