---
- name: Add go bin dir to $PATH if PATH does not exist
  shell: "cat /etc/profile |grep consul | wc -l"
  register: env_consul
- debug: msg="{{env_consul.stdout}}"

- name: "Add {{ consul_base_dir }} to PATH"
  lineinfile:
    path: "/etc/profile"
    state: present
    regexp: '(PATH=)(["]?)([\w|\/|\:]+)([\$PATH]+)(["]?)$'
    line: '\1\3{{ consul_base_dir }}:\4'
    backrefs: yes
  when: env_consul.stdout == "0"

- name: source "/etc/profile"
  shell: source /etc/profile && echo $PATH
  become: true
  args:
     executable: /bin/bash
  register: profile_status

- debug: msg="profile={{profile_status.stdout}}"