---
- name: Consul | Template out config
  template:
    src: "{{ role_path }}/templates/consul.json.j2"
    dest: "{{ consul_config }}/consul.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  #notify: restart consul

- name: Consul | Copy consul.service file
  template:
    src: "{{ role_path }}/templates/consul_systemd.service.j2"
    dest: /etc/systemd/system/consul.service
    trim_blocks: false
    mode: 0644
    owner: root
    group: root
  notify: restart consul