---

- name: Get consul binary
  get_url:
    url: "{{consul_file_url}}"
    dest: /tmp/
    checksum: sha256:{{consul_file_hash}}

- name: Unzip consul binary
  unarchive:
    src: /tmp/{{consul_file}}
    dest: "{{consul_bin_path}}"
    remote_src: true
    group: "{{consul_group}}"
    owner: "{{consul_user}}"
    mode: 0744