---
- hosts: t2
  # tasks:
  # - name: yum install ntpdate
  #   yum:
  #     name: ntp
  #     state: present
  # vars:
  #  - go_ver: '1.18.1'
  #  - go_platform: linux-amd64
  #  - url: 'https://go.dev/dl/go1.18.1.linux-amd64.tar.gz'
  roles:
   #- { role: Docker, become: yes }
   - { role: ini, become: yes }
   #- { role: ntpdate, become: yes, become_method: sudo }
  #    - { role: ntpdate, become: yes }