---
- name: reload mariadb
  service: 
    name: mariadb 
    state: reloaded
  become: true

- name: restart mariadb
  service: 
    name: mariadb 
    enabled: true
    state: stop
  become: true



