---
- name: restart redis
  vars:
    redis_port: "{{item}}"
  service: 
    name: "redis-{{redis_port}}"
    state: "restarted"
    enabled: true
  with_items: 
    - "{{redis_ports}}"
    

    
    
    
    
