---
- name: Install build-essential with "Ubuntu"
  apt: 
    name: build-essential
    state: latest
  become: true

- name: Install the libselinux-python package with "Ubuntu"
  apt: 
    name: python3-selinux 
    state: present
  become: true
  when: ansible_distribution_major_version >= "22"

- name: Disable SELinux with "Ubuntu"
  ansible.posix.selinux:
    configfile: /etc/selinux/semanage.conf 
    state: disabled
  become: true
