---
- name: Install build-essential with "Ubuntu"
  apt: 
    name: build-essential
    state: latest
  become: true

- name: Install the libselinux-python package with "Ubuntu"
  apt: 
    name: python3-selinux 
    state: present
  become: true
  when: ansible_distribution_major_version >= "22"

- name: Disable SELinux with "Ubuntu"
  ansible.posix.selinux:
    configfile: /etc/selinux/semanage.conf 
    state: disabled
  become: true


- name: apt install dependability on package for Ubuntu
  apt:
    name:
      - libreadline-dev
      - libncurses5-dev
      - libpcre3-dev
      - libssl-dev
      - perl
      - curl
      - geoip-bin
      - geoip-database
      - libgeoip-dev
      - libgeoip1
      - zlib1g
      - zlib1g-dev
      - net-tools
      - build-essential
      - htop
    state: present