---
- include_tasks: init-Redhat.yaml
  when: ansible_distribution == 'RedHat' or ansible_distribution == "Centos"

- include_tasks: init-Ubuntu.yaml
  when: ansible_distribution == "Ubuntu"





- name: Set timezone to Asia/Taipei
  timezone:
    name: Asia/Taipei
  become: true