---
- include_tasks: init-Redhat.yaml
  when: ansible_os_family == 'RedHat' or ansible_os_family == "Centos"

- include_tasks: init-Ubuntu.yaml
  when: ansible_os_family == "Ubuntu"





- name: Set timezone to Asia/Taipei
  timezone:
    name: Asia/Taipei
  become: true