---

- name: Check remote mariadb file exists
  stat: path="{{mariadb_APP_dir}}/mariadb"
  register: mariadb_install_path

- name: Check remote {{mariadb_APP_dir}}/{{mariadb_gz_file}} file exists
  stat: path="{{mariadb_APP_dir}}/{{mariadb_gz_file}}"
  register: mariadb_gz_status

- name: download file to mariadb_install_path  
  get_url:
    url: "{{mariadb_url}}"
    validate_certs: yes
    dest: "{{mariadb_APP_dir}}"
    force: yes
    checksum: "{{sha256sums_files}}"
  register: download_status
  when: (not mariadb_install_path.stat.exists) and (not mariadb_gz_status.stat.exists)

- name: "unarchive mariadb gz file"
  ansible.builtin.unarchive:
    src: "{{mariadb_APP_dir}}/{{mariadb_gz_file}}"
    dest: "{{mariadb_APP_dir}}"
    remote_src: true
  register: unarchive_status
  when: download_status is succeeded

- name: soft link{{mariadb_gz_file}} to mariadb
  ansible.builtin.file:
    src: "{{mariadb_APP_dir}}/mariadb-{{mariadb_version}}-{{mariadb_platform}}"
    dest: "{{mariadb_APP_dir}}/mariadb"
    state: link
    owner: "{{mariadb_user}}"
    group: "{{mariadb_group}}"
  when: unarchive_status is succeeded

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    owner: "{{mariadb_user}}"
    group: "{{mariadb_group}}"
    path: "{{item}}"
  with_items: 
      - "{{mariadb_APP_dir}}/mariadb"
      - "{{mariadb_APP_dir}}/mariadb-{{mariadb_version}}-{{mariadb_platform}}"
      - "{{mariadb_DB_dir}}"