---
- name: setup mariadb db 
  shell: "/opt/APP/mariadb/scripts/mysql_install_db --user={{mariadb_user}} --datadir={{mariadb_DB_dir}}"
  register: install_db_status

- debug: msg="{{install_db_status}}"