---
- name: Printing the environment mariadb in Ansible
  shell: "cat /etc/environment|grep mariadb | wc -l"
  register: env_mariadb
- debug: msg="{{env_mariadb.stdout}}"

- name: add {{mariadb_bin_path}} to path
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: '(PATH=["])(.*)(["])$'
    line: '\1\2:{{mariadb_bin_path}}\3'
    backrefs: yes
  when: env_mariadb.stdout == "0"

- name: source "/etc/environment"
  shell: source /etc/environment && echo $PATH
  become: true
  args:
     executable: /bin/bash
  register: profile_status

- debug: msg="profile={{profile_status.stdout}}"


- name: apt install package
  apt:
    name:
      - libncurses5
    state: latest
    update_cache: yes
  become: true