---

- name: redis-cluster-create-cluster | Set redis_cluster_master_ip_address_list
  ansible.builtin.set_fact:
    redis_cluster_master_ip_address_list: ""


- name: redis-cluster-create-cluster | Get all ip address with redis_role="master" in group
  ansible.builtin.set_fact:
        redis_cluster_master_ip_address_list: "{{ redis_cluster_master_ip_address_list + item  + ':'  ~ '%04d'|format(redis_ports[0]) }} "
  with_items: 
    - "{{ groups[redis_replication_nodes_group]}}"
  when: inventory_hostname ==  redis_replication_first_nodes

- name: redis-cluster-create-cluster | Set redis_cluster_slave_ip_address_list
  ansible.builtin.set_fact:
    redis_cluster_slave_ip_address_list: ""

- name: redis-cluster-create-cluster
  ansible.builtin.set_fact:
        redis_cluster_slave_ip_address_list: "{{ redis_cluster_slave_ip_address_list + item  + ':' ~ '%04d'|format(redis_ports[1]) }} "
  with_items: 
    - "{{ groups[redis_replication_nodes_group]}}"
  when: inventory_hostname ==  redis_replication_first_nodes

- debug: msg="{{redis_cluster_master_ip_address_list}}"
- debug: msg="{{redis_cluster_slave_ip_address_list}}"


- name: redis-cluster-create-cluster | Create redis cluster via redis-cli
  ansible.builtin.shell: "printf 'yes' | {{redis_bin_path}}/redis-cli -a {{redis_requirepass}} --cluster create {{ redis_cluster_master_ip_address_list + redis_cluster_slave_ip_address_list }}--cluster-replicas {{ redis_cluster_replica }}"
  run_once: True
  register: redis_cluster_created
  when: inventory_hostname ==  redis_replication_first_nodes


- debug: msg="{{redis_cluster_created}}"
