---


redis_version: 6.2.7
redis_gz_file: "{{redis_version}}.tar.gz"
redis_download: "https://github.com/redis/redis/archive/refs/tags/{{redis_gz_file}}"
replication: true
sentinel: false
cluster: false
#  redis_supervised systemd , auto ,no ,upstart
redis_supervised: "systemd"
redis_source_path: "/opt/source"
redis_app_path: "/opt/APP"
redis_log_path: "/opt/logs/redis"
redis_db_path: "/opt/db/redis"
redis_bin_path: "{{redis_app_path}}/redis/bin"
redis_conf_path: "{{redis_app_path}}/redis/redis.conf"
redis_user: "redis"
redis_group: "redis"
redis_daemon: "redis"

redis_bind: 0.0.0.0
redis_port: 6379
redis_timeout: 0
redis_daemonize: "no"
redis_loglevel: "notice"
redis_maxmemory: "256M"
# The working directory
redis_db_dir: "/opt/db/redis"
redis_pid_file: "/var/run/redis_6379.pid"
redis_logfile: "{{redis_log_path}}/redis-server.log"
redis_maxclients: "100"
# The filename where to dump the DB
redis_dbfilename: "dump.rdb"
# APPEND ONLY MODE
redis_appendonly: "no"
redis_appendfilename:  "appendonly.aof"
redis_dbdir: "{{redis_db_path}}"
redis_database: 16
redis_save:
  - save 3600 1
  - save 300 100
  - save 60 10000

## Redis Replication
redis_replication_nodes_group: "redis-replication-nodes"
redis_replication_first_nodes: "{{groups[redis_replication_nodes_group][0]}}"
redis_masteruser: "masteruser"
redis_masterauth: "Theeb7oose" 

##
redis_sentinel_conf_path: "{{redis_app_path}}/redis/sentinel.conf"
redis_sentinel_port: 26379
redis_sentinel_pidfile: "/var/run/redis-sentinel.pid"
redis_sentinel_logfile: "{{redis_log_path}}/sentinel.log"
redis_sentinel_master_name: "ckmaster"
redis_down_after_milliseconds: 10000
redis_failover_timeout: 18000