---
- name: Install docker-compose
  shell: "curl -SL https://github.com/docker/compose/releases/download/{{docker_compose_ver}}/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose"

- name: Change permissions for  docker-compose
  shell: chmod +x /usr/local/bin/docker-compose
