---
- include_tasks: Docker-Redhat.yaml
  when: ansible_distribution == 'RedHat' or ansible_distribution == "Centos"

- include_tasks: Docker-Ubuntu.yaml
  when: ansible_distribution == "Ubuntu"


- include_tasks: Docker-compose.yaml