---
- name: Install build-essential with "Ubuntu"
  apt: 
    name: build-essential
    state: latest
  become: yes
  when: ansible_distribution == "Ubuntu"

- name: Install the libselinux-python package with "Ubuntu"
  apt: 
    name: python3-selinux 
    state: present
  become: yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "22"

- name: Disable SELinux with "Ubuntu"
  ansible.posix.selinux:
    configfile: /etc/selinux/semanage.conf 
    state: disabled
  become: yes
  when: ansible_distribution == "Ubuntu"

- name: Disable SELinux with "RedHat"
  ansible.posix.selinux:
    state: disabled
  become: yes
  when: ansible_distribution == "Centos" and ansible_distribution == "RedHat"

- name: Set timezone to Asia/Taipei
  timezone:
    name: Asia/Taipei
  become: yes
  