---
#task:
- name: Disable Selinux
  Selinux: state=disabled
#- name: Disable Firewalld
#  service: name=firewalld state=stopped enabled=no

- name: Set timezone to Asia/Taipei
  timezone:
    name: Asia/Taipei
  become: yes
  